/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diagnostico;


import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tllach
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblTItulo = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnAgregarP = new javax.swing.JButton();
        btnObtener = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setForeground(new java.awt.Color(0, 153, 153));
        panel.setLayout(null);

        lblTItulo.setFont(new java.awt.Font("Book Antiqua", 0, 30)); // NOI18N
        lblTItulo.setForeground(new java.awt.Color(0, 204, 255));
        lblTItulo.setText("Bienvenid@ a tu lista enlazada");
        panel.add(lblTItulo);
        lblTItulo.setBounds(140, 30, 410, 40);

        lbl2.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lbl2.setText("¿Qué Desea Hacer?");
        panel.add(lbl2);
        lbl2.setBounds(240, 80, 210, 30);

        btnAgregarP.setText("Agregar una persona");
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });
        panel.add(btnAgregarP);
        btnAgregarP.setBounds(240, 140, 210, 50);

        btnObtener.setText("Obtener una persona");
        btnObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerActionPerformed(evt);
            }
        });
        panel.add(btnObtener);
        btnObtener.setBounds(240, 210, 210, 50);

        btnVisualizar.setText("Visualizar la lista");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        panel.add(btnVisualizar);
        btnVisualizar.setBounds(240, 280, 210, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
        showDialog(1);
        runAgregar();
    }//GEN-LAST:event_btnAgregarPActionPerformed

    private void btnObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerActionPerformed
        runObtener();
    }//GEN-LAST:event_btnObtenerActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        runVisualizar();
    }//GEN-LAST:event_btnVisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    public void showDialog(int i){
        switch(i){
            case 0:
                String okOpt = "Ok";
                Object[] options = {okOpt};
                n = JOptionPane.showOptionDialog(null,
                    "Persona Agregada" ,
                    "Persona Agregada ;)",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    options,
                    okOpt
                    );
                if(n == JOptionPane.YES_OPTION){
                    Diagnostico.listaPersonas.mostrar();
                }
                break;
            case 1:
                String yesOpt = "Empleado";
                String noOpt = "Cliente";
                options = new Object[]{yesOpt, noOpt};
                n = JOptionPane.showOptionDialog(null,
                        "¿Desea agregar un empleado o un Cliente" ,
                        "¿Empleado o Cliente?",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        yesOpt
                );
                break;
            case 2:
                okOpt = "Ok";
                options = new Object[]{okOpt};
                n = JOptionPane.showOptionDialog(null,
                        "Algunos de los datos esta incorrecto",
                        "Datos Incorrectos",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.ERROR_MESSAGE,
                        null,
                        options,
                        okOpt
                );
                if(n == JOptionPane.YES_OPTION){
                    runAgregar();
                }
                break;
            case 3:
                indexToSearch = (String) JOptionPane.showInputDialog(null,
                        "Ingrese el index de la persona a buscar",
                        "Buscando...",
                        JOptionPane.QUESTION_MESSAGE
                );
                
                break;
            case 4:
                okOpt = "Ok";
                options = new Object[]{okOpt};
                n = JOptionPane.showOptionDialog(null,
                    "Index No Encontrado" ,
                    "ERROR",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.ERROR_MESSAGE,
                    null,
                    options,
                    okOpt
                    );
                if(n == JOptionPane.YES_OPTION){
                    
                }
        }
        
    }
    
    
    public void runPrincipal(){
        panel.removeAll();
        
        lblTItulo = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnAgregarP = new javax.swing.JButton();
        btnObtener = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setForeground(new java.awt.Color(0, 153, 153));
        panel.setLayout(null);

        lblTItulo.setFont(new java.awt.Font("Book Antiqua", 0, 30)); // NOI18N
        lblTItulo.setForeground(new java.awt.Color(0, 204, 255));
        lblTItulo.setText("Bienvenid@ a tu lista enlazada");
        panel.add(lblTItulo);
        lblTItulo.setBounds(150, 30, 410, 40);

        lbl2.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lbl2.setText("¿Qué Desea Hacer?");
        panel.add(lbl2);
        lbl2.setBounds(240, 80, 210, 30);

        btnAgregarP.setText("Agregar una persona");
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });
        panel.add(btnAgregarP);
        btnAgregarP.setBounds(240, 140, 210, 50);

        btnObtener.setText("Obtener una persona");
        btnObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerActionPerformed(evt);
            }
        });
        panel.add(btnObtener);
        btnObtener.setBounds(240, 210, 210, 50);

        btnVisualizar.setText("Visualizar la lista");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        panel.add(btnVisualizar);
        btnVisualizar.setBounds(240, 280, 210, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        
        panel.revalidate();
        panel.repaint();
        pack();
    }
    
    public void runAgregar(){
        panel.removeAll();
        
        String a = "";
        if(n == 0){
            a = "Salario";
        }else{
            a = "Compras";
        }
        
        lbl = new javax.swing.JLabel() ;
        lbl.setFont(new java.awt.Font("Book Antiqua", 0, 30));
        lbl.setForeground(new java.awt.Color(0, 204, 255));
        lbl.setText("Llena los sgts datos");
        panel.add(lbl);
        lbl.setBounds(210, 25, 410, 40);
        
        btnAgregar = new JButton();
        panel.add(btnAgregar);
        btnAgregar.setText("Agregar");
        btnAgregar.setBounds(440, 160, 200, 50);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(areTxtsCorrect()){
                    agregarPersonas(n);
                    showDialog(0);
                    runAgregar();
                }
            }
        });
        
        volverBtn = new JButton();
        panel.add(volverBtn);
        volverBtn.setText("Volver");
        volverBtn.setBounds(440, 240, 200, 50);
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runPrincipal();
            }
        });
        
        
        lblVar = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();

        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtVar = new javax.swing.JTextField();
        
        txtNombre.setText("");
        panel.add(txtNombre);
        txtNombre.setBounds(100, 100, 260, 40);

        txtApellido.setText("");
        panel.add(txtApellido);
        txtApellido.setBounds(100, 180, 260, 40);

        txtId.setText("");
        panel.add(txtId);
        txtId.setBounds(100, 250, 260, 40);

        txtVar.setText("");
        panel.add(txtVar);
        txtVar.setBounds(100, 330, 260, 40);

        lblVar.setFont(new java.awt.Font("Agency FB", 1, 24)); 
        lblVar.setText(a);
        panel.add(lblVar);
        lblVar.setBounds(100, 295, 120, 30);

        lblName.setFont(new java.awt.Font("Agency FB", 1, 24)); 
        lblName.setText("Nombre");
        panel.add(lblName);
        lblName.setBounds(100, 60, 70, 40);

        lblApellido.setFont(new java.awt.Font("Agency FB", 1, 24));
        lblApellido.setText("Apellido");
        panel.add(lblApellido);
        lblApellido.setBounds(100, 145, 70, 30);

        lblID1.setFont(new java.awt.Font("Agency FB", 1, 24));
        lblID1.setText("ID");
        panel.add(lblID1);
        lblID1.setBounds(100, 220, 30, 30);
        
        panel.revalidate();
        panel.repaint();
    }
    
    public void runObtener(){
        Empleado empleado;
        Cliente cliente;
        String nombreP = "";
        String apellidoP = "";
        String idP = "";
        String varP = "";

        lbl = new javax.swing.JLabel() ;
        lbl.setFont(new java.awt.Font("Book Antiqua", 0, 30));
        lbl.setForeground(new java.awt.Color(0, 204, 255));
        lbl.setText("Datos");
        
        lbl.setBounds(290, 25, 410, 40);
        
        
        volverBtn = new JButton();
        
        volverBtn.setText("Volver");
        volverBtn.setBounds(460, 330, 210, 50);
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runPrincipal();
            }
        });
        
        
        lblVar = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();

        

        lblName.setFont(new java.awt.Font("Agency FB", 1, 24)); 
        lblName.setText("Nombre");
        
        lblName.setBounds(100, 60, 70, 40);

        lblApellido.setFont(new java.awt.Font("Agency FB", 1, 24));
        lblApellido.setText("Apellido");
        
        lblApellido.setBounds(100, 145, 70, 30);

        lblID1.setFont(new java.awt.Font("Agency FB", 1, 24));
        lblID1.setText("ID");
        
        lblID1.setBounds(100, 220, 30, 30);
        
        showDialog(3);
        try{
            int indexToSearch = Integer.parseInt(this.indexToSearch) - 1;
            if(indexToSearch <= Diagnostico.listaPersonas.getTam()){
                try{
                    empleado = (Empleado) Diagnostico.listaPersonas.obtener(indexToSearch);
                    nombreP = empleado.getNombre();
                    apellidoP = empleado.getApellido();
                    idP = String.valueOf(empleado.getId());
                    varP = String.valueOf(empleado.getSalario());
                    n = 0;
                }catch(Exception e){}
                try{
                    cliente = (Cliente) Diagnostico.listaPersonas.obtener(indexToSearch);
                    nombreP = cliente.getNombre();
                    apellidoP = cliente.getApellido();
                    idP = String.valueOf(cliente.getId());
                    varP = String.valueOf(cliente.getCompras());
                    n = 1;
                }catch(Exception e){}
                panel.removeAll();
            
                String a = "";
                if(n == 0){
                    a = "Salario";
                }else{
                    a = "Compras";
                }

                panel.add(lbl);
                panel.add(volverBtn);

                lblVar.setFont(new java.awt.Font("Agency FB", 1, 24)); 
                lblVar.setText(a);
                panel.add(lblVar);
                lblVar.setBounds(100, 295, 120, 30);

                panel.add(lblName);
                panel.add(lblApellido);
                panel.add(lblID1);

                lblNameInfo = new javax.swing.JLabel();
                lblApellidoInfo = new javax.swing.JLabel();
                lblID1Info = new javax.swing.JLabel();
                lblVarInfo = new javax.swing.JLabel();

                lblNameInfo.setText(nombreP);
                lblNameInfo.setFont(new java.awt.Font("Candara Light", 0, 24));
                panel.add(lblNameInfo);
                lblNameInfo.setBounds(100, 100, 300, 40);

                lblApellidoInfo.setText(apellidoP);
                lblApellidoInfo.setFont(new java.awt.Font("Candara Light", 0, 24));
                panel.add(lblApellidoInfo);
                lblApellidoInfo.setBounds(100, 180, 300, 40);

                lblID1Info.setText(idP);
                lblID1Info.setFont(new java.awt.Font("Candara Light", 0, 24));
                panel.add(lblID1Info);
                lblID1Info.setBounds(100, 250, 300, 40);

                lblVarInfo.setText(varP);
                lblVarInfo.setFont(new java.awt.Font("Candara Light", 0, 24));
                panel.add(lblVarInfo);
                lblVarInfo.setBounds(100, 330, 300, 40);

                panel.revalidate();
                panel.repaint();
            
            }else{
                showDialog(4);
            }
            
        }catch(Exception e){}
    }
    
    public void runVisualizar(){
        panel.removeAll();
        
        createTabla();
        
        lblTItulo = new javax.swing.JLabel();
        lblTItulo.setFont(new java.awt.Font("Book Antiqua", 0, 30));
        lblTItulo.setForeground(new java.awt.Color(0, 204, 255));
        lblTItulo.setText("Lista");
        panel.add(lblTItulo);
        lblTItulo.setBounds(300, 30, 100, 40);
        
        volverBtn = new JButton();
        panel.add(volverBtn);
        volverBtn.setText("Volver");
        volverBtn.setBounds(270, 360, 130, 30);
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt){
                runPrincipal();
            }
        });
        
        agregarDatos();
        
        panel.revalidate();
        panel.repaint();
    }
    
    public void createTabla(){
        modelTable = new DefaultTableModel(
                null,
                new String[]{"Tipo", "Nombre", "Apellido", "ID", ""} 
        );
        tableCliente = new JTable(modelTable);
        scrollPane = new JScrollPane(tableCliente);
        
        panel.add(scrollPane);
        scrollPane.setBounds(100, 90, 520, 250);
    }
    
    public void agregarDatos(){
        String tipo;
        String nombre;
        String apellido;
        String id;
        String var;
        
        int tam = Diagnostico.listaPersonas.getTam();
        for(int i = 0; i < tam; i++){
            Persona p = Diagnostico.listaPersonas.obtener(i);
            if(p.getTipo() == "Cliente"){
                Cliente j = (Cliente) p;
                var = String.valueOf(j.getCompras());
            }else{
                Empleado j = (Empleado) p;
                var = String.valueOf(j.getSalario());
            }
            tipo = p.getTipo();
            nombre = p.getNombre();
            apellido = p.getApellido();
            id = String.valueOf(p.getId());
            Object[] k = new Object[]{tipo, nombre, apellido, id, var};
            modelTable.addRow(k);
        }

    }
    
    public void agregarPersonas(int i){
        if(i == 0){
            Diagnostico.listaPersonas.agregar(new Empleado(txtNombre.getText(), txtApellido.getText(), Long.parseLong(txtId.getText()), Float.parseFloat(txtVar.getText())));
        }else{
            Diagnostico.listaPersonas.agregar(new Cliente(txtNombre.getText(), txtApellido.getText(), Long.parseLong(txtId.getText()), Integer.parseInt(txtVar.getText())));
        }
        
    }
    
    public boolean areTxtsCorrect(){
        
        try{
            Long i = Long.parseLong(txtId.getText());
            Float j = Float.parseFloat(txtVar.getText());
        }catch(Exception e){
            showDialog(2);
            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnObtener;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblTItulo;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    private int n;
    private String indexToSearch;
    private javax.swing.JLabel lbl;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton volverBtn;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtVar;
    private javax.swing.JLabel lblVar;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblVarInfo;
    private javax.swing.JLabel lblNameInfo;
    private javax.swing.JLabel lblApellidoInfo;
    private javax.swing.JLabel lblID1Info;
    private JTable tableCliente;
    private DefaultTableModel modelTable;
    private JScrollPane scrollPane;
}
